Fix a number of Injection related issues
AdoptOpenJDK/openjdk-api-v3 pull request #332
Opened 2020-12-07 22:40 UTC by johnoliver

- Fix packaging so that injection works live
- Add GraphQL tests

Unrelated fix:
- Don't apply version sanity checks to user supplied versions

# Checklist

- [ ] You added tests to cover the change
- [ ] `mvn clean install` build and test completes
- [ ] You changed or added to the documentation

2020-12-08 13:19 UTC, karianna requested changes
Nitpicks and a bit of a lingering question on if we've added DI why is there more code now? Question

2020-12-08 13:19 UTC, karianna commented on adoptopenjdk-api-v3-persistence/src/main/kotlin/net/adoptopenjdk/api/v3/dataSources/APIDataStore.kt
> +
remove whitespace

2020-12-08 13:19 UTC, karianna commented on adoptopenjdk-api-v3-updater/src/main/kotlin/net/adoptopenjdk/api/v3/V3Updater.kt
>  import java.util.*
java.util.*

2020-12-08 13:19 UTC, karianna commented on adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/AdoptReposBuilderTest.kt
> +    /*
remove commented code

2020-12-08 13:19 UTC, karianna commented on adoptopenjdk-api-v3-updater/src/test/kotlin/net/adoptopenjdk/api/ReleaseVersionResolverTest.kt
>  import net.adoptopenjdk.api.v3.dataSources.*
Exapnd * import

2020-12-08 13:50 UTC, johnoliver commented
@karianna the addition of code is mostly from:
- we are now testing GraphQl classes that were previously not testable so that added code. 
- we had not fully removed our dependency on having `example-data.json.gz` in the code base for tests. That has now been fully removed and we generate test data, again that added more code.
- A fair number of the additions are just xml files or annotations needed in place to configure the DI

2020-12-08 16:47 UTC, karianna approved these changes

2020-12-09 09:42 UTC, karianna commented
@johnoliver - I'm happy to land if you fix the nitpicks :-)

2020-12-09 13:44 UTC, johnoliver commented
@karianna done

2020-12-09 16:50 UTC, merged